apiVersion: v1
kind: Template
metadata:
  name: gateway-template
  annotations:
    openshift.io/display-name: ocean gateway Service
    iconClass: fa fa-code
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${APP_NAME}:latest
          name: ${APP_NAME}
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8250
              scheme: TCP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8250
              scheme: TCP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 4
              memory: 512Mi
            requests:
              cpu: 1
              memory: 512Mi
          env:
          - name: HELLO_MESSAGE
            value: ${HELLO_MESSAGE}
          - name: HELLO_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: HELLO_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HELLO_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                key: hello.environment
                name: ${APP_NAME}
          ports:
          - containerPort: 8250
            protocol: TCP
    triggers: 
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8250-tcp
      port: 8250
      protocol: TCP
      targetPort: 8250
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
- apiVersion: v1
  kind: ConfigMap
  metadata: 
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  data:
    hello.environment: ${ENVIRONMENT}
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: hello-service
- description: Git Repository
  displayName: Git Repository
  name: GIT_REPO
  required: true
  value: ssh://git@gitlab.frxs.cn:2222/wenglifeng/ocean-gateway.git
- description: Git Branch
  displayName: Git Branch
  name: GIT_BRANCH
  required: true
  value: master
- name: HELLO_MESSAGE
  displayName: Hello Message
  description: Hello Message
  required: true
  value: "welcome to ocean-gateway!"
- name: ENVIRONMENT
  displayName: Environment
  description: Environment
  required: true
  value: dev